# Custom Language File for Launcher Customizer

[ejs.app]
title = "ION Launcher"

[ejs.landing]
mediaGitHubURL = "https://www.ion-network.de"
mediaTwitterURL = "#"
mediaInstagramURL = "https://instagram.ion-network.de"
mediaYouTubeURL = "https://youtube.ion-network.de"
mediaDiscordURL = "https://discord.gg/BNpBnrerCs"

[ejs.settings]
sourceGithubLink = "https://github.com/IONNetworkTeam/IONLauncher"
supportLink = "https://github.com/IONNetworkTeam/IONLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO ION Network"
welcomeDescription = "With this Launcher you can easily connect to VelonaSMP and other Minecraft Servers powered by ION Network."
welcomeDescCTA = "You are just a few clicks away."
